# Generated by Django 3.2 on 2021-04-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ld48', '0002_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='post',
            name='average_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='n_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
